### PR TITLE
Hdp contacts strange characters

### PR DESCRIPTION
**Pull request by sraby**
- made a "clean-up" file that updates values in hpd_contacts by replacing strange character combinations representing NULL values with true NULLs

NOTE: this branch is based off of @romeboards rentstab summary PR, so it should be merged after his

### CODE REVIEW

**Comment by aepyornis** [comment]
cool! I suggest squashing all those merge commits...

**Comment by sraby** [comment]
@aepyornis isn't that something you do when you merge the PR? Or would you like me to squash from my end to update it?

**Comment by aepyornis** [comment]
try this:

```
git rebase -i d9378bf04de84d85db122d4758f34e6610bab9bb
```

**Comment by sraby** [comment]
Alright, tried that @aepyornis. Those extra merge commits have been squashed. Not sure why it's still adding in the rentstab summary commits as those are already merged...

**Pull request merged**
